bcgov/EMCR-DRR-PORTAL

drr/src/API/EMCR.DRR/Controllers/ApplicationController.cs
drr/src/API/EMCR.DRR/EMCR.DRR.csproj
drr/src/API/EMCR.DRR/Program.cs
drr/src/API/EMCR.DRR/Resources/Applications/ApplicationRepository.cs
drr/src/API/EMCR.DRR/Resources/Applications/Contract.cs
drr/src/API/EMCR.DRR/Resources/Applications/Mappings.cs
drr/src/API/EMCR.Test.Integration.DRR.Api/Application.cs
drr/src/API/EMCR.Test.Integration.DRR.Api/Resources/ApplicationTests.cs

Hooked up POST endpoint to map the data and save it in dynamics.
Added integration test for creating a new drif application.

Enable saving to dynamics

---

drr/src/UI/src/app/step-3/step-3.component.html

[DRR-122] step validation error added;
[DRR-113] stepper made vertical for mobile view;
[DRR-114] phone input allows only numbers and set limit to 10;
[DRR-118] hazards description fixed;
[DRR-123] submit error message with steps; 
and funding step remaining amount fix

DRR-122, DRR-113, DRR-114, DRR-118, DRR-123 introduced

---

drr/src/UI/package-lock.json
drr/src/UI/package.json
drr/src/UI/src/app/app.config.ts
drr/src/UI/src/app/drr-input/drr-input.component.html
drr/src/UI/src/app/drr-input/drr-input.component.ts
drr/src/UI/src/app/step-1/step-1.component.html
drr/src/UI/src/app/step-1/step-1.component.ts
drr/src/UI/src/app/step-2/step-2.component.html
drr/src/UI/src/app/step-2/step-2.component.ts
drr/src/UI/src/app/step-8/step-8.component.html
drr/src/UI/src/app/summary/summary.component.html
drr/src/UI/src/app/summary/summary.component.ts

[DRR-115] if sameAsSubmitter project contact fields display values 
[DRR-115] sameAsSubmitter subscription fix
[DRR-126] only positive numeric input for number input
[DRR-114] phone number format enforced
[DRR-114] phone number summary fixed
[DRR-125] min start date set to today; min end date set to min start

DRR-115, DRR-126, DRR-114, DRR-125 fixed;

---

drr/src/UI/src/app/drr-datepicker/drr-textarea.component.html
drr/src/UI/src/app/drr-datepicker/drr-textarea.component.ts
drr/src/UI/src/app/drr-input/drr-input.component.html
drr/src/UI/src/app/drr-input/drr-input.component.ts
drr/src/UI/src/app/eoi-application/eoi-application.component.ts

[DRR-173] vertical mode scroll to top introduced
[DRR-174] drr input and textarea labels mobile view fix

[DRR-172] [DRR-173] [DRR-174] addressed

---

drr/src/UI/src/app/eoi-application/eoi-application.component.html
drr/src/UI/src/app/eoi-application/eoi-application.component.ts
drr/src/UI/src/app/footer/footer.component.html
drr/src/UI/src/app/footer/footer.component.ts
drr/src/UI/src/app/step-1/step-1.component.html
drr/src/UI/src/app/step-1/step-1.component.scss
drr/src/UI/src/app/step-2/step-2.component.html
drr/src/UI/src/app/step-3/step-3.component.html
drr/src/UI/src/app/step-3/step-3.component.scss
drr/src/UI/src/app/step-5/step-5.component.html
drr/src/UI/src/app/step-5/step-5.component.scss
drr/src/UI/src/app/summary/summary.component.scss
drr/src/UI/src/assets/i18n/en.json
drr/src/UI/src/index.ts
drr/src/UI/src/model/contactDetails.ts
drr/src/UI/src/model/drifEoiApplication.ts
drr/src/UI/src/model/fundingInformation.ts
drr/src/UI/src/styles/styles.scss

[DRR-181] mobile view styling fixed
[DRR-181] mobile view summary fixed
[DRR-162] [DRR-163] footer header changes applied
[DRR-175] clearing error message if successfully submitted

[DRR-181] [DRR-181] [DRR-162] [DRR-163] [DRR-175] addressed

---

drr/src/UI/src/app/footer/footer.component.html
drr/src/UI/src/app/footer/footer.component.ts

[DRR-136] both versions are displayed

[DRR-136] both versions are displayed

---

drr/src/UI/src/app/drr-currency-input/drr-currency-input.component.html
drr/src/UI/src/app/drr-currency-input/drr-currency-input.component.scss
drr/src/UI/src/app/drr-currency-input/drr-currency-input.component.spec.ts
drr/src/UI/src/app/drr-currency-input/drr-currency-input.component.ts
drr/src/UI/src/app/drr-datepicker/drr-datepicker.component.html
drr/src/UI/src/app/drr-datepicker/drr-datepicker.component.ts
drr/src/UI/src/app/drr-input/drr-input.component.html
drr/src/UI/src/app/drr-input/drr-input.component.scss
drr/src/UI/src/app/drr-input/drr-input.component.ts
drr/src/UI/src/app/drr-select/drr-select.component.ts
drr/src/UI/src/app/drr-textarea/drr-textarea.component.ts
drr/src/UI/src/app/eoi-application/eoi-application-form.ts
drr/src/UI/src/app/step-2/step-2.component.html
drr/src/UI/src/app/step-2/step-2.component.ts
drr/src/UI/src/app/step-3/step-3.component.html
drr/src/UI/src/app/step-3/step-3.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-212] currency input component created
[DRR-223] mandatory mark fixed
[DRR-212] currency error improved
[DRR-210] date picker error messages improved
[DRR-210] date picker min end date fix

[DRR-212] [DRR-223] [DRR-212] [DRR-210] [DRR-210] addressed

---

drr/src/UI/src/app/drr-input/drr-input.component.html
drr/src/UI/src/app/drr-input/drr-input.component.ts
drr/src/UI/src/app/step-5/step-5.component.html
drr/src/UI/src/assets/i18n/en.json

[DRR-236] estimatedPeopleImpacted 9 digits
[DRR-224] email field enhanced

[DRR-236] [DRR-224] addressed

---

drr/src/UI/src/app/summary/summary.component.html
drr/src/UI/src/assets/i18n/en.json

[DRR-244] estimatedPeopleImpacted label fixed
[DRR-201] remaining funds summary label changed

[DRR-244] [DRR-201] addressed

---

drr/src/UI/cypress/e2e/spec.cy.ts
drr/src/UI/src/app/dashboard/submission-list/submission-list.component.html
drr/src/UI/src/app/drif/drif-submission-details/drif-submission-details.component.ts
drr/src/UI/src/app/drif/eoi-application/eoi-application-form.ts
drr/src/UI/src/app/drif/eoi-application/eoi-application.component.ts
drr/src/UI/src/app/drif/step-1/step-1.component.html
drr/src/UI/src/app/drif/step-1/step-1.component.ts
drr/src/UI/src/app/drif/step-8/step-8.component.html
drr/src/UI/src/app/drif/step-8/step-8.component.scss
drr/src/UI/src/app/drif/step-8/step-8.component.ts
drr/src/UI/src/app/drif/summary/summary.component.html
drr/src/UI/src/app/drif/summary/summary.component.ts
drr/src/UI/src/app/shared/controls/drr-input/drr-input.component.scss
drr/src/UI/src/assets/i18n/en.json

[[DRR-376] [DRR-302] submitter prefilled and moved to step 8

[[DRR-376] [DRR-302] submitter prefilled and moved to step 8

---

drr/src/UI/src/app/app.routes.ts
drr/src/UI/src/app/dashboard/submission-list/submission-list.component.html
drr/src/UI/src/app/drif/eoi-application/eoi-application.component.ts
drr/src/UI/src/app/drif/step-8/step-8.component.ts

[DRR-376] reset submitter if last save author is different
[DRR-372] save new EOI redirects to edit mode child route
submission list hide edit button if under review

[DRR-376] [DRR-372] changes

---

drr/src/UI/src/app/core/auth/auth.service.ts
drr/src/UI/src/app/drif/summary-item/summary-item.component.html
drr/src/UI/src/app/drif/summary-item/summary-item.component.scss
drr/src/UI/src/app/drif/summary/summary.component.scss

[DRR-281] summary page items view improved; token logging removed; 
token refresh error triggers logout to reset authentication

[DRR-281] summary page items view improved; token logging removed; token refresh error logout

---

drr/src/landing-page/src/html/index-dev.html
drr/src/landing-page/src/html/index-localhost.html
drr/src/landing-page/src/html/index-prod.html
drr/src/landing-page/src/html/index-test.html

[DRR-326] landing page CRAFT section content
[DRR-327] landing page DMAP section content
contact section padding increased

[DRR-326] [DRR-327] implemented

---

drr/src/UI/src/app/drif/drif-eoi/drif-eoi.component.ts
drr/src/landing-page/src/html/index-dev.html
drr/src/landing-page/src/html/index-localhost.html
drr/src/landing-page/src/html/index-prod.html
drr/src/landing-page/src/html/index-test.html

[DRR-562] submit redirect to list with success message
[DRR-272] login section updated

[DRR-562] [DRR-272] 

---

drr/src/API/EMCR.DRR/Controllers/DRIFApplicationController.EOI.cs
drr/src/API/EMCR.DRR/Controllers/DRIFApplicationController.FP.cs
drr/src/API/EMCR.DRR/Controllers/DRIFApplicationController.cs
drr/src/API/EMCR.DRR/Managers/Intake/IntakeManager.cs
drr/src/API/EMCR.DRR/Resources/Applications/ApplicationRepository.cs
drr/src/UI/src/app/drif/drif-eoi/drif-eoi.component.ts
drr/src/landing-page/src/html/index-dev.html
drr/src/landing-page/src/html/index-localhost.html
drr/src/landing-page/src/html/index-prod.html
drr/src/landing-page/src/html/index-test.html

API permissions and error handling improvements

merge release/1.1.0 into develop

---

drr/src/UI/src/app/core/interceptors/error.interceptor.ts
drr/src/UI/src/app/drif/drif-eoi/drif-eoi.component.ts

[DRR-540] 403 error message
[DRR-562] submit message changed

[DRR-562] [DRR-540]

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-9/drif-fp-step-9.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/app/shared/controls/drr-chip-autocomplete/drr-chip-autocomplete.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-460] professionals comments added
[DRR-581] risks mandatory logic added
[DRR-581] risks mandatory logic added

[DRR-460] [DRR-581] [DRR-581] related changes

---

drr/src/UI/src/app/dashboard/submission-list/submission-list.component.scss
drr/src/UI/src/app/drif/drif-eoi/drif-eoi.component.ts

[DRR-601] filter out empty critical infrastructure values
[DRR-611] submission list table header color changed

[DRR-601] [DRR-611] fixed

---

drr/src/UI/src/app/dashboard/submission-list/submission-list.component.html
drr/src/UI/src/app/drif/drif-eoi-step-3/drif-eoi-step-3.component.html
drr/src/UI/src/app/drif/drif-eoi-step-3/drif-eoi-step-3.component.ts
drr/src/UI/src/app/drif/drif-eoi/drif-eoi-form.ts
drr/src/UI/src/app/drif/drr-funding-list/drr-funding-list.component.html
drr/src/UI/src/app/drif/drr-funding-list/drr-funding-list.component.scss
drr/src/UI/src/app/drif/drr-funding-list/drr-funding-list.component.spec.ts
drr/src/UI/src/app/drif/drr-funding-list/drr-funding-list.component.ts
drr/src/UI/src/app/drif/summary/summary.component.html
drr/src/landing-page/src/html/index-dev.html
drr/src/landing-page/src/html/index-localhost.html
drr/src/landing-page/src/html/index-prod.html
drr/src/landing-page/src/html/index-test.html

[DRR-615] other funding question added
[DRR-642] date formatting fixed

[DRR-615] [DRR-642] addressed

---

drr/src/landing-page/src/html/index-dev.html
drr/src/landing-page/src/html/index-localhost.html
drr/src/landing-page/src/html/index-prod.html
drr/src/landing-page/src/html/index-test.html

[DRR-613] landing page restyled, all 4 index pages changed

[DRR-613] landing page restyled

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-step-2/drif-fp-step-2.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/maintenance-page/src/html/index-localhost.html

stepper auto save fix; land ownership comment fix; maintenance page

---

drr/src/UI/src/api/configuration/configuration.service.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-2/drif-fp-step-2.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/index.ts
drr/src/UI/src/model/draftFpApplicationAllOf.ts
drr/src/UI/src/model/standardInfo.ts

[DRR-460] standard category checkboxes
[DRR-564] return to submission list after FP submit
[DRR-472] submit FP

[DRR-460] [DRR-564] [DRR-472] addressed

---

drr/src/UI/src/app/drif/drif-eoi/drif-eoi-step-5/drif-eoi-step-5.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.ts
drr/src/UI/src/app/submission-list/submission-list.component.html
drr/src/UI/src/app/submission-list/submission-list.component.ts
drr/src/UI/src/assets/i18n/en.json
drr/src/landing-page/src/html/index-dev.html
drr/src/landing-page/src/html/index-localhost.html
drr/src/landing-page/src/html/index-prod.html
drr/src/landing-page/src/html/index-test.html

[DRR-717] critical infra button fixed
[DRR-381] default sorting issue fixed
[DRR-380] filtering empty responses handled
professionals issue fixed
[DRR-719] landing page acronym fixed

[DRR-717] [DRR-381] [DRR-380] [DRR-719] addressed

---

drr/src/UI/src/api/drifapplication/drifapplication.service.ts
drr/src/UI/src/app/drif/drif-eoi/drif-eoi-summary/drif-eoi-summary.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-summary/drif-fp-summary.component.html
drr/src/UI/src/app/submission-list/submission-list.component.html
drr/src/UI/src/app/submission-list/submission-list.component.scss
drr/src/UI/src/app/submission-list/submission-list.component.ts
drr/src/UI/src/assets/i18n/en.json
drr/src/UI/src/index.ts
drr/src/UI/src/model/submissionPortalStatus.ts

[DRR-282] withdraw application dialog added
[DRR-282] withdraw API calls
[DRR-948] EOI summary page fixed
[DRR-382] delete application added

[DRR-282] [DRR-948] [DRR-382]

---

drr/src/UI/src/app/core/auth/auth.service.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-11/drif-fp-attachment.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-11/drif-fp-step-11.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-summary/drif-fp-summary.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-summary/drif-fp-summary.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/app/shared/controls/drr-chip-autocomplete/drr-chip-autocomplete.component.scss
drr/src/UI/src/app/shared/controls/drr-chip-autocomplete/drr-chip-autocomplete.component.ts
drr/src/UI/src/app/shared/services/file.service.ts

[DRR-463] attachment forms implementation
[DRR-737] summary file download introduced
[DRR-1152] standards mandatory if selected
[DRR-1150] autocomplete control improved; long text; clear input after selection

[DRR-463] [DRR-737] [DRR-1152] [DRR-1150] addressed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-step-11/drif-fp-attachment.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-11/drif-fp-step-11.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-463] resolution document checkbox
[DRR-463] attachment comments textarea and layout improved

[DRR-463] attachment resolution fix & comments textarea

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-instructions/drif-fp-instructions.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-screener/drif-fp-screener.component.html
drr/src/UI/src/app/shared/controls/drr-input/drr-input.component.ts
drr/src/UI/src/app/shared/footer/footer.component.html

[DRR-1102] numeric input limit fixed
[DRR-897] instructions page ad 6 fixed; 
[DRR-1192] screener header fixed;
[DRR-1195] footer contact us link added.

[DRR-1102] [DRR-897] [DRR-1192] [DRR-1195] footer contact us link added.

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-screener/drif-fp-screener.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-1214] hide standards if not applicable
[DRR-990] screener text fixed
[DRR-1217] screener links target fixed

[DRR-1214] [DRR-990] [DRR-1217] addressed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-6/drif-fp-step-6.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-summary/drif-fp-summary.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-view/drif-fp-view.component.ts
drr/src/UI/src/app/shared/controls/drr-file-upload/drr-file-upload.component.ts

[DRR-1243] FP declaration error fixed; upload message changed to 50mb… 
[DRR-1244] FP step 12 summary fixed
[DRR-1245] climate assessment summary fixed
[DRR-1247] attachment summary view fixed
[DRR-1249] summary labels fixed

[DRR-1243] [DRR-1244] [DRR-1245] [DRR-1247] [DRR-1249] bugs addressed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-screener/drif-fp-screener.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-1219] step 10 validation fixed
[DRR-1259] at least one standard selected validation fixed
[DRR-1254] screener support email issue fixed

[DRR-1219] [DRR-1259] [DRR-1254] bugs fixed

---

drr/src/UI/src/app/app.config.ts
drr/src/UI/src/app/core/interceptors/error.interceptor.ts
drr/src/UI/src/app/drif/drif-eoi/drif-eoi.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/app/shared/controls/drr-file-upload/drr-file-upload.component.ts
drr/src/landing-page/src/html/index-prod.html

[DRR-1269] close toast to prevent from overlapping
[DRR-1298] tracking form changes fixed

[DRR-1269] [DRR-1298] addressed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-screener/drif-fp-screener.component.html

[DRR-1369] screener alerts changed to use DMAP email
[DRR-1370] screener project workplan alert changed

[DRR-1369] [DRR-1370] screener alerts changed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-step-4/drif-fp-step-4.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html

[DRR-1165] label issue fixed
[DRR-1373] note margin fixed

[DRR-1165] label issue fixed [DRR-1373] note margin fixed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-step-11/drif-fp-step-11.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-4/drif-fp-step-4.component.html
drr/src/UI/src/app/shared/controls/drr-file-upload/drr-file-upload.component.ts

[DRR-1373] instruction label changed
[DRR-1322] new attachment form touched after delete
[DRR-1362] file upload toast issue fixed

[DRR-1373] [DRR-1322] [DRR-1362] addressed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-summary/drif-fp-summary.component.scss
drr/src/UI/src/app/drif/drif-fp/drif-fp-view/drif-fp-view.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts

[DRR-1165] label hidden
[DRR-1167] label issue fixed; init array items count fixed

[DRR-1165] [DRR-1167] labels fixed; array issue fixed

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-4/drif-fp-step-4.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-4/drif-fp-step-4.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-summary/drif-fp-summary.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-view/drif-fp-view.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.ts
drr/src/UI/src/assets/i18n/en.json
drr/src/UI/src/index.ts
drr/src/UI/src/model/draftFpApplicationAllOf.ts
drr/src/UI/src/model/proposedActivity.ts

[DRR-1448] FP predefined activities 
[DRR-1518] cost estimates

[DRR-1448] FP predefined activities  [DRR-1518] cost estimates 

---

drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.ts
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-form.ts
drr/src/UI/src/app/drif/drif-project/drif-project.component.html
drr/src/UI/src/app/drif/drif-project/drif-project.component.scss
drr/src/UI/src/app/shared/controls/drr-datepicker/drr-datepicker.component.html
drr/src/UI/src/app/shared/controls/drr-datepicker/drr-datepicker.component.ts
drr/src/UI/src/assets/i18n/en.json
drr/src/UI/src/model/workplanActivity.ts
drr/src/UI/src/model/workplanStatus.ts

[DRR-1694] mandatory comment condition prepared
[DRR-1692] new additional controls and applicable conditions added
[DRR-1692] WorkplanStatus API enum used
[DRR-1692] WorkplanStatus labels
[DRR-1699] progress report dates rules

[DRR-1699] [DRR-1692] [DRR-1694] progress report activities

---

drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.ts
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-form.ts
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-summary/drif-progress-report-summary.component.html
drr/src/UI/src/assets/i18n/en.json

[DRR-1686] instructions text added
[DRR-1710] future events form layout

[DRR-1686] instructions text added [DRR-1710] future events form layout

---

drr/src/UI/src/app/app.config.ts
drr/src/UI/src/app/drif/drif-eoi/drif-eoi.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-create/drif-progress-report-create.component.ts
drr/src/UI/src/app/drif/drif-project/drif-progress-report/drif-progress-report-summary/drif-progress-report-summary.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-1718] save on navigation
[DRR-1716] reset checkboxes if form changed
[DRR-1687] progress report step validation fixed
[DRR-1721] submit validation and error handling

[DRR-1718] [DRR-1716] [DRR-1687] [DRR-1721] saving, validation, declaration & submit 

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.ts
drr/src/UI/src/app/shared/controls/drr-currency-input/drr-currency-input.component.html
drr/src/UI/src/app/shared/controls/drr-currency-input/drr-currency-input.component.ts
drr/src/UI/src/assets/i18n/en.json

[DRR-2019] new total project cost layout; new comment field added; cu… 
[DRR-2020] FP budget funding request section
[DRR-2021] new cost estimate class layout
[DRR-2022] detailed cost estimate instructions
[DRR-2023] contingency filtered for stream 1 projects

FP Step 10 Budget new layout

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.ts
drr/src/UI/src/app/shared/controls/drr-number-input/drr-number-input.component.ts

[DRR-2026] [DRR-2027] contingency and total estimate cost calculation… 
[DRR-2027] continency class threshold calculation
[DRR-2027] continency threshold layout

[DRR-2026] [DRR-2027] total estimates & contingency calculation & threshold 

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-form.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.html
drr/src/UI/src/app/drif/drif-fp/drif-fp-step-10/drif-fp-step-10.component.ts
drr/src/UI/src/app/drif/drif-fp/drif-fp.component.ts
drr/src/UI/src/assets/i18n/en.json
drr/src/UI/src/model/progressReportStatus.ts

[DRR-2027] contingency calc fixed
[DRR-2032] remaining amount calculation adjusted
[DRR-2032] project cost fix
[DRR-2032] remaining amount calculation adjusted

[DRR-2027] [DRR-2032] addressed

---

drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-forecast/drif-forecast-create/drif-forecast-create.component.html

[DRR-1776] claim instructions
[DRR-1918] forecast instructions

Forecast & claim instructions added

---

drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.scss
drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.ts
drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-form.ts
drr/src/UI/src/app/drif/drif-project/drif-project-contact-dialog.component.ts
drr/src/UI/src/app/drif/drif-project/drif-project-contact-form.ts
drr/src/UI/src/app/drif/drif-project/drif-project.component.html
drr/src/UI/src/app/drif/drif-project/drif-project.component.scss
drr/src/UI/src/app/drif/drif-project/drif-project.component.ts
drr/src/UI/src/assets/i18n/en.json

create claims preparation
project view improvements

create claims preparation & project view improvements

---

drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.html
drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.ts
drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-form.ts
drr/src/UI/src/app/drif/drif-project/drif-project.component.html
drr/src/UI/src/app/drif/drif-project/drif-project.component.ts
drr/src/UI/src/model/interimReport.ts
drr/src/UI/src/model/projectStatus.ts

[DRR-1874] report alias added
claim init logic

[DRR-1874] report alias added

---

drr/src/UI/src/app/drif/drif-fp/drif-fp-step-7/drif-fp-step-7.component.html
drr/src/UI/src/app/drif/drif-project/drif-claim/drif-claim-create/drif-claim-create.component.html

[DRR-2598] invoice attachments margin increased
[DRR-1434] permit input changed to textarea

[DRR-2598] invoice attachments margin increased [DRR-1434] permit input changed to textarea

---

drr/src/UI/src/app/drif/drif-project/drif-forecast/drif-forecast-create/drif-forecast-create.component.ts
drr/src/UI/src/app/drif/drif-project/drif-forecast/drif-forecast-summary/drif-forecast-summary.component.html

[DRR-2656] forecast summary view mandatoriness fixed
[DRR-2657] forecast submit declarations

[DRR-2657] [DRR-2656] fixed
